/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bpa_project_XInputNative */

#ifndef _Included_bpa_project_XInputNative
#define _Included_bpa_project_XInputNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bpa_project_XInputNative
 * Method:    getState
 * Signature: (ILjava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_bpa_1project_XInputNative_getState
  (JNIEnv *, jclass, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
