/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class XInputNative */

#ifndef _Included_XInputNative
#define _Included_XInputNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     XInputNative
 * Method:    getState
 * Signature: (ILjava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_XInputNative_getState
  (JNIEnv *, jclass, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
